const AdminDetail = require("../models/AdminDetail.js");

class AdminDetailController {
  static addAdminDetail = async (req, res) => {
    const { username, password } = req.body;
    if (username && password) {
      try {
        let str = "EUR-ADMIN-";
        let x = Date.now().toString(8);
        let y = x.toString().substr(-3);
        let z = Math.floor(Math.random() * 1000);
        let autoGeneratedAdminID = str + y + z;
        const newAdmin = new AdminDetail({
          admin_id: autoGeneratedAdminID,
          username: username,
          password: password,
        });
        newAdmin.save();
        res.status(200).json({ message: "New Admin Added" });
      } catch (error) {
        res.status(500).json({ message: "Failed to Add New Admin" });
      }
    } else {
      res.send({ status: "Failed", message: "Fill All Fields" });
    }
  };

  static findAdmin = async (req, res) => {
    const { username, password } = req.body;
    try {
      const verifyAdmin = await AdminDetail.find({
        username: username,
        password: password,
      });
      res.status(200).json({ verifyAdmin });
    } catch (error) {
      res.send({
        status: "Failed",
        message: "Failed to Find Admin",
      });
    }
  };
}

module.exports = AdminDetailController;
